config/routes.rb
Rails.application.routes.draw do
  resources :weathers

  resources :temps

  resources :lists

  resources :cities

  resources :forecasts

  resources :locations

  get 'sessions/create'

  
  root "welcome#index"
  get "about" => "welcome#about", as: :about
  get "blog" => "welcome#blog", as: :blog
  
  
  
   match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
   match 'auth/failure', to:  redirect("/") , via: [:get, :post]

   match 'signout', to: 'sessions#signout', via: [:get, :post]
   
   match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]

   match 'customtweets', to: 'welcome#customtweets', via: [:get] 
   match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
   

end

app/models/temp.rb
class Temp < ActiveRecord::Base
end

app/controllers/temps_controller.rb
class TempsController < ApplicationController
  before_action :set_temp, only: [:show, :edit, :update, :destroy]

  # GET /temps
  # GET /temps.json
  def index
    @temps = Temp.all
  end

  # GET /temps/1
  # GET /temps/1.json
  def show
  end

  # GET /temps/new
  def new
    @temp = Temp.new
  end

  # GET /temps/1/edit
  def edit
  end

  # POST /temps
  # POST /temps.json
  def create
    @temp = Temp.new(temp_params)

    respond_to do |format|
      if @temp.save
        format.html { redirect_to @temp, notice: 'Temp was successfully created.' }
        format.json { render :show, status: :created, location: @temp }
      else
        format.html { render :new }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temps/1
  # PATCH/PUT /temps/1.json
  def update
    respond_to do |format|
      if @temp.update(temp_params)
        format.html { redirect_to @temp, notice: 'Temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @temp }
      else
        format.html { render :edit }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temps/1
  # DELETE /temps/1.json
  def destroy
    @temp.destroy
    respond_to do |format|
      format.html { redirect_to temps_url, notice: 'Temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temp
      @temp = Temp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temp_params
      params.require(:temp).permit(:day, :min, :max, :night, :eve, :morn)
    end
end

app/helpers/temps_helper.rb
module TempsHelper
end

app/views/temps/_form.html.erb
<%= form_for(@temp) do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :min %><br>
    <%= f.text_field :min %>
  </div>
  <div class="field">
    <%= f.label :max %><br>
    <%= f.text_field :max %>
  </div>
  <div class="field">
    <%= f.label :night %><br>
    <%= f.text_field :night %>
  </div>
  <div class="field">
    <%= f.label :eve %><br>
    <%= f.text_field :eve %>
  </div>
  <div class="field">
    <%= f.label :morn %><br>
    <%= f.text_field :morn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temps/edit.html.erb
<h1>Editing Temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

app/views/temps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temps</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Min</th>
      <th>Max</th>
      <th>Night</th>
      <th>Eve</th>
      <th>Morn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temps.each do |temp| %>
      <tr>
        <td><%= temp.day %></td>
        <td><%= temp.min %></td>
        <td><%= temp.max %></td>
        <td><%= temp.night %></td>
        <td><%= temp.eve %></td>
        <td><%= temp.morn %></td>
        <td><%= link_to 'Show', temp %></td>
        <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
        <td><%= link_to 'Destroy', temp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temp', new_temp_path %>

app/views/temps/new.html.erb
<h1>New Temp</h1>

<%= render 'form' %>

<%= link_to 'Back', temps_path %>

app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @temp.day %>
</p>

<p>
  <strong>Min:</strong>
  <%= @temp.min %>
</p>

<p>
  <strong>Max:</strong>
  <%= @temp.max %>
</p>

<p>
  <strong>Night:</strong>
  <%= @temp.night %>
</p>

<p>
  <strong>Eve:</strong>
  <%= @temp.eve %>
</p>

<p>
  <strong>Morn:</strong>
  <%= @temp.morn %>
</p>

<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>