config/routes.rb
Rails.application.routes.draw do
  resources :weathers

  resources :temps

  resources :lists

  resources :cities

  resources :forecasts

  resources :locations

  get 'sessions/create'

  
  root "welcome#index"
  get "about" => "welcome#about", as: :about
  get "blog" => "welcome#blog", as: :blog
  
  
  
   match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
   match 'auth/failure', to:  redirect("/") , via: [:get, :post]

   match 'signout', to: 'sessions#signout', via: [:get, :post]
   
   match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]

   match 'customtweets', to: 'welcome#customtweets', via: [:get] 
   match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
   

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SurfDub</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <% if current_user %>
         <li>  Signed in as <%= current_user.name %></li>
        <li><%= link_to "Sign out", signout_path %></li>
        <li class="<%= yield(:index) %>"><%= link_to "Home", root_path %></li> 
        <li class="<%= yield(:about) %>"><%= link_to "about", about_path %></li>
        <li class="<%= yield(:blog) %>"><%= link_to "blog", blog_path %></li>
        
        <% else %>
        <li><%= link_to "Sign in with google", "/auth/google_oauth2" %></li>
        <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>